<?php namespace ProcessWire;

class MarkupSitemapXML extends WireData implements Module, ConfigurableModule
{

    public $cacheTime;
    private $multilang;

    /**
     * Provide information about this module to ProcessWire
     *
     */
    public static function getModuleInfo()
    {
        return array(
            'title' => 'Markup Sitemap XML',
            'summary' => 'Generates an XML sitemap at yoursite.com/sitemap.xml for use with Google Webmaster Tools etc.',
            'href' => 'http://processwire.com/talk/index.php/topic,867.0.html',
            'version' => 127,
            'permanent' => false,
            'autoload' => true,
            'singular' => true,
        );
    }

    /**
     * Add the hook
     *
     */
    public function init()
    {

        $this->cacheTime = 3600;
        $urlParams = '';
        $this->multilang = false;

        // load js only on this page
        if ($this->wire('input')->get('name') == $this->className) {

            // add flag to js config to process with module js file
            if ($this->wire('session')->MarkupSitemapXML_generateSitemap == 1) {
                $this->wire('config')->js("MarkupSitemapXML_generateSitemap", true);
            }

            // save generateSitemap request to session no prevent redirect loss on submit
            if ($this->wire('input')->post('submit_save_module')) {
                $this->wire('session')->MarkupSitemapXML_generateSitemap = 1;
            } else {
                $this->wire('session')->remove('MarkupSitemapXML_generateSitemap');
            }

            $this->config->scripts->add($this->config->urls->siteModules . 'MarkupSitemapXML/MarkupSitemapXML.js');
        }

        if ($this->wire('input')->get('nocache') == 1) {
            $this->cacheTime = 0;
            $urlParams = '?nocache=1';
        }

        // Intercept a request for an URL ending in sitemap.xml and output
        if (isset($_SERVER['REQUEST_URI']) && strlen($_SERVER['REQUEST_URI']) - strlen('/sitemap.xml' . $urlParams) === strrpos($_SERVER['REQUEST_URI'], '/sitemap.xml' . $urlParams)) {
            //do not use addHookBefore here, because it will brake multi language support due the late hook of Page::localHttpUrl
            $this->addHookAfter("ProcessPageView::pageNotFound", $this, "renderSitemap");
        }
    }


    public static function getModuleConfigInputfields(array $data)
    {

        $inputfields = new InputfieldWrapper();

        // add exclude list field (textarea)
        $field = wire('modules')->get('InputfieldTextarea');
        $field->name = 'sitemap_exclude_list';
        $field->label = __("Exclude list");
        // $field->value = array_key_exists('sitemap_exclude_list', $data) ? $data['sitemap_exclude_list'] : '';
        $field->description = __('Matching pages will be excluded from the sitemap. Add one selector per line.');
        $field->notes = __('Examples: "title=My Page Title" or "template=my-template" or "parent.path=/my-page/" (without quotes)');
        if (isset($data['sitemap_exclude_list'])) $field->value = $data['sitemap_exclude_list'];
        $inputfields->add($field);

        return $inputfields;
    }

    public function renderSitemap(HookEvent $event)
    {
        //$event->replace = true;
        $lang = '';
        $this->pageselector = '';
        $langname = ''; // for LanguageLocalizedUrl
        $subdomain = ''; // for Multisite

        // set startPage according to request (sitemap.xml spec says that sitemap
        // should only contain pages below it's root page in page tree)
        // Fix #11 by FlipZoomMedia | David Karich
        $startPage = str_ireplace(trim($this->wire('config')->urls->root, '/'), '', $this->sanitizer->path(dirname($_SERVER['REQUEST_URI'])));

        // Multisite requires minor URL-related tweak
        if ($this->wire("modules")->isInstalled("Multisite")) {
            $multiSite = $this->wire("modules")->get("Multisite");
            if ($multiSite->subdomain) {
                $startPage = "/" . $multiSite->subdomain . $startPage;
            }
        }

        // make sure that page used as root for sitemap actually exists
        if ($this->pages->get($startPage) instanceof NullPage) return;

        // support for LanguageLocalizedURL language module
        if ($this->wire("modules")->isInstalled("LanguageSupport")) {
            $this->multilang = true;
        }
        // Check for the cached sitemap, else generate and cache a fresh sitemap
        $startpagestr = $this->sanitizer->pageName($startPage);
        $cache = $this->wire('modules')->get("MarkupCache");
        if (!$output = $cache->get("MarkupSitemapXML$startpagestr$langname", $this->cacheTime)) {
            $output = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
            $output .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
            $output .= $this->sitemapListPage($this->wire('pages')->get($startPage));
            $output .= "\n</urlset>";
            $cache->save($output);
        }
        header("Content-Type: text/xml", true, 200);
        echo $output;
        exit();
    }

    /**
     * Check if Page matches user-entered exclude selector list
     *
     * @param $page
     * @return bool true if match found
     *
     */

    public function isPageExcluded($page)
    {
        // get module settings
        $configData = $this->wire('modules')->getModuleConfigData($this);

        // process exclude list
        if ($configData['sitemap_exclude_list'] != '') {

            $excludeList = trim($configData['sitemap_exclude_list']);
            $excludeList = explode("\n", $excludeList);
            $excludeList = array_filter($excludeList, 'trim'); // remove any extra \r characters left behind

            // loop through lines of exclude list
            foreach ($excludeList as $item) {

                // skip items starting with "//" (commented out)
                if (substr($item, 0, 2) === '//') {
                    continue;
                }

                if ($page->is($item)) {
                    return true;
                }
            }
        }

        return false;
    }

    private function renderSitemapEntry($url, $modified)
    {
        return "<url>\n"
        . "<loc>{$url}</loc>\n"
        . "<lastmod>{$modified}</lastmod>\n"
        . "</url>\n";

    }

    public function sitemapListPage($page)
    {
        $entry = "";
        if ($page->viewable()
            && ($page->sitemap_ignore == 0 || $page->path == '/')// $page->path part added so that it ignores hiding the homepage, else you wouldn't have ANY pages returned
            && !$this->isPageExcluded($page)
        ) {
            $modified = date('Y-m-d', $page->modified);
            if (!$this->multilang) {
                $entry .= $this->renderSitemapEntry($page->httpUrl, $modified);
            } else {
                foreach ($page->getLanguages() as $lang) {
                    $entry .= $this->renderSitemapEntry($page->localHttpUrl($lang), $modified);
                }
            }
        }

        // Fix #12 by FlipZoomMedia | David Karich
        $children = $page->children($this->pageselector);
        if (count($children)) {
            foreach ($children as $child) {
                $entry .= $this->sitemapListPage($child);
            }
        }
        return $entry;
    }

    /**
     * Install the module
     *
     */
    public function ___install()
    {

        if ($this->fields->get('sitemap_ignore')) {
            $this->error("You already have a 'sitemap_ignore' field.");
            return;
        }

        $this->wire('modules')->get('MarkupCache');

        $field = new Field();
        $field->type = $this->modules->get("FieldtypeCheckbox");
        $field->name = 'sitemap_ignore';
        $field->label = 'Hide page from XML sitemap';
        $field->description = 'Hide this page and its children from the XML sitemap';
        $field->save();

        $this->message("Added field 'sitemap_ignore'. Add this field to any templates where you want to prevent inclusion in the XML sitemap.");
    }

    /**
     * Uninstall the module
     *
     */
    public function ___uninstall()
    {
        // only do the following if you want to uninstall the fields that were installed
        // this may be one thing that's safe to leave to the user
        $field = $this->wire('fields')->get('sitemap_ignore');
        if ($field && $field->numFieldgroups() > 0)
            throw new WireException("Can't uninstall because field sitemap_ignore is still being used. Please remove it from any templates.");
        if ($field)
            $this->wire('fields')->delete($field);
    }
}
